package com.ovh.soapi.manager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-18T14:52:00.150+02:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://soapi.ovh.com/manager", name = "managerPortType")
public interface ManagerPortType {

    @WebResult(name = "return", targetNamespace = "http://soapi.ovh.com/manager")
    @RequestWrapper(localName = "telephonySmsUserSend", targetNamespace = "http://soapi.ovh.com/manager", className = "com.ovh.soapi.manager.TelephonySmsUserSend")
    @WebMethod
    @ResponseWrapper(localName = "telephonySmsUserSendResponse", targetNamespace = "http://soapi.ovh.com/manager", className = "com.ovh.soapi.manager.TelephonySmsUserSendResponse")
    public int telephonySmsUserSend(
        @WebParam(name = "login", targetNamespace = "http://soapi.ovh.com/manager")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "http://soapi.ovh.com/manager")
        java.lang.String password,
        @WebParam(name = "smsAccount", targetNamespace = "http://soapi.ovh.com/manager")
        java.lang.String smsAccount,
        @WebParam(name = "numberFrom", targetNamespace = "http://soapi.ovh.com/manager")
        java.lang.String numberFrom,
        @WebParam(name = "numberTo", targetNamespace = "http://soapi.ovh.com/manager")
        java.lang.String numberTo,
        @WebParam(name = "message", targetNamespace = "http://soapi.ovh.com/manager")
        java.lang.String message,
        @WebParam(name = "smsValidity", targetNamespace = "http://soapi.ovh.com/manager")
        java.lang.Integer smsValidity,
        @WebParam(name = "smsClass", targetNamespace = "http://soapi.ovh.com/manager")
        java.lang.Integer smsClass,
        @WebParam(name = "smsDeferred", targetNamespace = "http://soapi.ovh.com/manager")
        java.lang.Integer smsDeferred,
        @WebParam(name = "smsPriority", targetNamespace = "http://soapi.ovh.com/manager")
        java.lang.Integer smsPriority,
        @WebParam(name = "smsCoding", targetNamespace = "http://soapi.ovh.com/manager")
        java.lang.Integer smsCoding,
        @WebParam(name = "tag", targetNamespace = "http://soapi.ovh.com/manager")
        java.lang.String tag,
        @WebParam(name = "noStop", targetNamespace = "http://soapi.ovh.com/manager")
        java.lang.Boolean noStop
    );
}
