-- @Text Drop table renewal_perischool_activities_request_regime_alimentaire_renouvellement

alter table renewal_perischool_activities_request_regime_alimentaire_renouvellement 
    drop constraint if exists FK8AFF2E83E35CAE2;

alter table renewal_perischool_activities_request_regime_alimentaire_renouvellement 
    drop constraint if exists FK8AFF2E837F587126;

drop table if exists renewal_perischool_activities_request_regime_alimentaire_renouvellement cascade;
