drop table learning_activities_discovery_registration_request_choix1;
drop table learning_activities_discovery_registration_request_choix2;
drop table learning_activities_discovery_registration_request_choix3;
